### ISSUE TITLE
optimization for training

### ISSUE THREAD

**Issue by innat** [sayakpaul/dreambooth-keras#23]
@sayakpaul @deep-diver 

In the [code example](https://keras.io/examples/generative/dreambooth/), it's mentioned that 

> If you're running the code, please ensure you're using a GPU with at least 24 GBs of VRAM.

So, running this code example on colab looks not possible (even with bs = 1). The official [diffusers](https://huggingface.co/docs/diffusers/main/en/training/dreambooth#finetuning) guide shows some ways to make it possible to run dreambooth on vram with less than 24. Some of the suggested techniques may be hacky to achieve in tf. Could you please inform:

- do you have any future plan to support dreambooth-keras for (at least) 16GB device?
- have you tried on tpu device?

**Comment by sayakpaul** [comment]
Possible on Colab Pro Plus that provides access to A100. No, we don't have plans to support the two points you mentioned.
